# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6f2d8a098ad25eade9b58b96e17c60ec53b815de96745b0bbdb7f4d322d966fb22a746e47eacf4efe7583a9e59372051b5051154c2ba37e2da9ae91f402b36c

test:
  secret_key_base: 5383d6688256345cb875beea6764b43e9cc02496e8935ce66a70192cd7734073cdd645f3d512501a25b7d2d1507fd79683c320a8c28c8ff9293c1a54556d0f85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
